/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {MigrationsContract} from "./Migrations";
import {StorageContract} from "./Storage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "Storage"): StorageContract;
    }
  }
}

export {MigrationsContract, MigrationsInstance} from "./Migrations";
export {StorageContract, StorageInstance} from "./Storage";
